//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string room { get; set; }
        public Nullable<int> porch { get; set; }
        public Nullable<int> floor { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
