//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersSale.Models
{
    using FlowersSale.Utils;
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string src { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }

        public String FullSrc
        {
            get
            {
                String src = $"{Constants.CATEGORY_IMAGE_PATH}\\{this.src}";
                if (!File.Exists(src))
                {
                    return $"{Constants.CATEGORY_IMAGE_PATH}\\no_photo.png";
                }
                return src;
            }
        }
    }
}
