//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersSale.Models
{
    using FlowersSale.Utils;
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.ItemsOrder = new HashSet<ItemsOrder>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string src { get; set; }
        public decimal price { get; set; }
        public int id_categories { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsOrder> ItemsOrder { get; set; }
        public String FullSrc
        {
            get
            {
                String src = $"{Constants.ITEM_IMAGE_PATH}\\{this.src}";
                if (!File.Exists(src))
                {
                    return $"{Constants.ITEM_IMAGE_PATH}\\no_photo.png";
                }
                return src;
            }
        }
    }
}
