//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowersSale.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class FlowersSaleEntities : DbContext
    {
        private static FlowersSaleEntities _context;

        public static FlowersSaleEntities GetContext()
        {
            if (_context == null)
                _context = new FlowersSaleEntities();
            return _context;
        }

        public void Reload()
        {
            this.ChangeTracker.Entries().ToList().ForEach(v => v.Reload());
        }

        public FlowersSaleEntities()
            : base("name=FlowersSaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ItemsOrder> ItemsOrder { get; set; }
    }
}
